### PR TITLE
Add S3_EXTRA_OPTIONS to customize command

### PR DESCRIPTION
**Pull request by tkhduracell**
Allow customisation of the S3 upload command.

Use case: Change endpoint.
```
S3_EXTRA_OPTIONS=--endpoint=https://s3.customprovider.net
```
 
After feedback, added `S3_STORAGE_CLASS`.

### CODE REVIEW

**Comment by tkhduracell** [comment]
@heyman A PR for you! :)

**Comment by heyman** [comment]
Thanks!

Maybe it would make sense to add all of the following environment variables:

* `S3_STORAGE_CLASS`: Defaults to `STANDARD_IA`
* `S3_EXTRA_OPTIONS`: Defaults to empty string, and can be used to add additional command line parameters without overwriting the storage class
* `S3_OPTIONS`:  If specified it will override the two previous options. Otherwise it will be constructed from the `S3_STORAGE_CLASS` and `S3_EXTRA_OPTIONS` as well as any other options we might add in the future.

What do you think?

**Comment by tkhduracell** [comment]
Thanks for looking at this. I had a little bit of conflicting feelings whether S3_STORAGE_CLASS should be needed at all since it's just another "S3 option". However, since it is a backup tools after all, it kind of makes sense to be clear about storage classes. 

Not sure if S3_OPTIONS need to be option at all. Since you can do everything with S3_STORAGE_CLASS + S3_EXTRA_OPTIONS.?

**Comment by tkhduracell** [comment]
@heyman Updated PR

**Comment by heyman** [comment]
> Not sure if S3_OPTIONS need to be option at all. Since you can do everything with S3_STORAGE_CLASS + S3_EXTRA_OPTIONS.?

My thinking was that there might be situations where you don't want to set the storage class parameter at all. E.g. if you're using an S3 API  that isn't AWS, and doesn't support the storage class parameter.

**Comment by heyman** [comment]
I've now fixed the integration tests to use the `zenko/cloudserver` image as S3 substitute. Once this has been merged we should be able to merge master into the other PR:s to get the tests working there as well.

**Comment by heyman** [comment]
Merged this now! Great work! The `S3_OPTIONS` could be added at a later time if deemed necessary.

**Pull request merged**
