### PR TITLE
Add DB_USE_ENV to use PG env vars instead of requiring DB_*

### PR DESCRIPTION
**Pull request by tkhduracell**
Add option to rely solely on [postgres environment variables](https://www.postgresql.org/docs/13/libpq-envars.html) from the environment.

### CODE REVIEW

**Comment by tkhduracell** [comment]
@heyman More things :)

**Comment by heyman** [comment]
Nice!

Maybe it would be nice to add additional test steps to the Github CI actions for this, once the fixed CI fixes in #11 have been merged?

**Comment by tkhduracell** [comment]
@heyman Something like this? Could potentially use matrix instead for this, but since it was multiple input variables that need to change it seemed cumbersome.

**Comment by heyman** [comment]
Nice!

**Pull request merged**
