### PR TITLE
Add WEBHOOK_CURL_OPTS and WEBHOOK_DATA

### PR DESCRIPTION
**Pull request by tkhduracell**
Add two parameters and make the new data parameter interpolated with metadata. 

Use case is for example: Slack webhook 
```
WEBHOOK=https://hooks.slack.com/services/<redacted>/<redacted>
WEBHOOK_METHOD=POST
WEBHOOK_DATA={"text":":white_check_mark: Backup completed at %(date)s %(time)s\nDuration: %(duration)s seconds\nUpload: %(filename)s: %(size)s"}
WEBHOOK_CURL_OPTS=-H 'Content-type: application/json'
```

### CODE REVIEW

**Comment by tkhduracell** [comment]
@heyman Another PR for you! :) 
Could you help out with the CI build?

**Comment by heyman** [comment]
Looks great, thanks!

Minor thing, but I think i'd prefer `WEBHOOK_CURL_OPTIONS` instead of `WEBHOOK_CURL_OPTS`.

It wold also be great to add your Slack webhook example to the Readme, under the "Interpolation" section.

**Comment by heyman** [comment]
> Could you help out with the CI build?

I think it's failing because it won't have access the repository secrets where I've added working S3 credentials for a test bucket on my account. I'm now thinking that it would probably be better to spin up a [cloudserver](https://s3-server.readthedocs.io/en/latest/DOCKER.html) container (with `S3BACKEND=mem`) to test against, instead of AWS.

**Comment by tkhduracell** [comment]
@heyman Updated PR

**Pull request merged**
